name: Python CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 Linter
        run: pip install flake8 && flake8 .

      - name: Run Bandit (Security Scan)
        run: pip install bandit && bandit -r .

      - name: Run Safety (Dependency Security Check)
        run: pip install safety && safety check --full-report
