name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 linter
        run: |
          pip install flake8
          flake8 .

      - name: Run Safety scan
        run: |
          pip install safety
          safety scan --file=requirements.txt --full-report

      - name: Run Bandit security scan
        run: |
          pip install bandit
          bandit -r .

      - name: Push changes using GitHub token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }}.git
          git push origin main
