name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Added pytest installation

    - name: Authenticate with Safety CLI
      run: echo "SAFETY_API_KEY=${{ secrets.SAFETY_API_KEY }}" >> $GITHUB_ENV

    - name: Run Safety scan
      run: safety scan

    - name: Run tests
      run: |
        pytest  # This will now run after pytest is installed

    - name: Upload coverage results
      uses: codecov/codecov-action@v3

